### ISSUE TITLE
Težava z definiranjem simpleks množice v pythonu

### ISSUE THREAD

**Issue by AnzeMarinko** [AccipitrisArti/Razvrscanje-z-dominantnimi-mnozicami#2]
@jaanos Težavo imava z definiranjem simpleksa v pythonu (datoteka algoritem_razvrščanje).
Bi to morala definirati kot diskretno množico?
Kako bi se bilo tega pametno lotiti?
`Delta = set() \n
for j in R^n: \n
   ...`?

**Comment by jaanos** [comment]
Vsekakor v Pythonu (ali v kateremkoli drugem programskem jeziku) ne bo mogoče definirati množice, ki bo vsebovala neskončno elementov.

Je pa seveda možno tako množico opisati - en očiten način bi bil, da se podajo omejitve, ki veljajo za to množico. Potem je npr. možno preveriti, ali se nek element nahaja v tej množici. Kakšna predstavitev bo ustrezna, pa je seveda odvisno od tega, kaj želita s tako množico početi.
