### ISSUE TITLE
RuntimeWarning med izvajanjem programa

### ISSUE THREAD

**Issue by AnzeMarinko** [AccipitrisArti/Razvrscanje-z-dominantnimi-mnozicami#5]
@jaanos Ko poženeva program nama včasih izpiše opozorilo:

> RuntimeWarning: invalid value (oz. včasih divide by zero) encountered in double_scalars
>   konstanta = - mx / (my - mx)

To je ukaz v 45. vrstici kode. Program pa sicer še vedno izvede.
Kako se izogneva temu problemu?

**Comment by jaanos** [comment]
Do tega pride, kot je vrednost `my - mx` enaka 0 (ali zelo blizu nje). Ker v tem primeru pogoj ne bo izpolnjen, lahko enostavno to prej preverita in vrneta ustrezno vrednost.
