### ISSUE TITLE
Problem z grupiranjem

### ISSUE THREAD

**Issue by AnzeMarinko** [AccipitrisArti/Razvrscanje-z-dominantnimi-mnozicami#6]
@jaanos
program (razvrscanje.py) nama ne pobarva tock pravilno (bolj podobne tocke bi morale bit v isti gruci), torej bi morale bit tocke na nekem intervalu tudi iste barve na sliki ... bi bilo bolje kako drugace definirati, katera tocka je v gruci in katera ne?

              if gruce[i] == 0:
                    if itr[1][komp] > 10 ** (-(20-natancnost) / len(vektor)) / len(vektor):
                        gruce[i] = gruca

kjer je natancnost neko fiksno stevilo, vektor pa vektor stevil, ki mu zelimo dolociti gruce.
Ali pa je le 50 iteracij premalo, da bi resitev dovolj skonvergirala k ravnovesni tocki.

**Comment by AnzeMarinko** [comment]
z nekaj popravki, mislim da je ze dosti bolje, bi pa raje videl, da bi bilo stevilo gruc bolj odvisno od parametra natancnost, kot od dolzine vektorja ...
imate kaksen nasvet, kako, bi ohranjal stabilnost algoritma tudi za vektorje vecjih dimenzij?

**Comment by jaanos** [comment]
Zdaj imaš:

https://github.com/AccipitrisArti/Razvrscanje-z-dominantnimi-mnozicami/blob/280ba9a8390969af4052cbd6c6393f84d4c42f9f/razvrscanje.py#L159-L160

Preverjaš torej, ali trenutna komponenta presega nek delež največje komponente. Ali je sploh smiselno, da dolžina vektorja vpliva na ta delež? Morda lahko poskusiš to deljenje odstraniti.

**Comment by AnzeMarinko** [comment]
@jaanos v kodi sem popravil vecino danes omenjenih napak, zanima me le se, kako bi lahko 159. vrstico se poboljsal (tista grda potenca), ker ta mislim, da enostavno mora bit odvisna od len(kor) in max(itr[1]), sicer so gruce prevec razlicno velike.

**Comment by jaanos** [comment]
V bistvu je že `max(itr[1])` odvisen od `len(kor)`, saj velja `max(itr[1]) * len(kor) >= 1`, z enakostjo, ko so vse komponente vektorja `kor` enake (in so torej `1/len(kor)`). Velikosti samih gruč so lahko različne - bolj pomembno je, da so elementi v isti gruči bližje skupaj (v praksi majhne gruče pogosto predstavljajo osamelce - podatke, ki so tako posebni, da jih velja v splošni analizi morda izločiti).

**Comment by AnzeMarinko** [comment]
Hvala! na to možnost sem kar malo pozabil, ker sem se omejil na 10**(- ___)
